# Generated by Django 6.0.5 on 2026-05-14 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Доступность репетитора',
                'verbose_name_plural': 'Расписание репетиторов',
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.JSONField(default=list)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_currency', models.CharField(default='KZT', max_length=10)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('education', models.TextField(blank=True)),
                ('education_level', models.CharField(choices=[('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'Доктор наук'), ('student', 'Студент'), ('other', 'Другое')], default='bachelor', max_length=20)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('format', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн'), ('both', 'Онлайн и оффлайн')], default='online', max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('video_intro_url', models.URLField(blank=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('languages', models.JSONField(default=list)),
                ('trial_lesson_available', models.BooleanField(default=False)),
                ('trial_lesson_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Профиль репетитора',
                'verbose_name_plural': 'Профили репетиторов',
            },
        ),
    ]
